package co.edu.tdea.bank.domain.ports.in;

import co.edu.tdea.bank.domain.models.Transfer;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Input port — initiates a new fund transfer between two bank accounts.
 * Accounts and the creator user are resolved internally from their repositories.
 * The transfer identifier is generated by the persistence layer, not supplied by the caller.
 */
public interface CreateTransferUseCase {

    /**
     * @param sourceAccountNumber      number of the account to be debited
     * @param destinationAccountNumber number of the account to be credited
     * @param amount                   amount to transfer; must be > 0
     * @param createdByUserId          UUID of the user initiating the transfer
     * @param creationDateTime         moment the transfer is initiated
     * @param approvalThreshold        minimum amount from which explicit approval is required
     * @return the saved {@link Transfer}, either in {@code PENDING_APPROVAL} or {@code EXECUTED}
     */
    Transfer createTransfer(String sourceAccountNumber,
                            String destinationAccountNumber,
                            BigDecimal amount,
                            UUID createdByUserId,
                            LocalDateTime creationDateTime,
                            BigDecimal approvalThreshold);
}
