package co.edu.tdea.bank.domain.ports.in;

import co.edu.tdea.bank.domain.enums.LoanType;
import co.edu.tdea.bank.domain.models.Loan;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Input port — submits a new loan request on behalf of a client.
 * The client and linked user are resolved internally from their repositories.
 * The loan identifier is generated by the persistence layer, not supplied by the caller.
 */
public interface RequestLoanUseCase {

    /**
     * @param clientId        UUID of the client submitting the request
     * @param loanType        type of credit product being requested
     * @param requestedAmount amount the client wishes to borrow; must be > 0
     * @param termInMonths    desired repayment term in months; must be > 0
     * @return the newly created {@link Loan} in {@code UNDER_REVIEW} status
     */
    Loan requestLoan(UUID clientId,
                     LoanType loanType,
                     BigDecimal requestedAmount,
                     Integer termInMonths);
}
